/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz.grafica;


import Conexion.Conexion;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import javax.swing.JOptionPane;


import javax.swing.*;
import java.sql.*;
import static java.util.Objects.hash;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.mindrot.jbcrypt.BCrypt;


import java.util.ResourceBundle;
import javax.swing.JOptionPane;
/**
 *
 * @author Jhoan
 */
public class JF_Login extends javax.swing.JFrame {
    
    Properties datosProps = new Properties();
       Properties jfLoginProps = new Properties();
     
       public void cargarproperties() 
     {   
         
        try {
            datosProps.load(new FileInputStream("D:\\Documentos\\NetBeansProjects\\contratacion\\src\\main\\java\\packagesproperties\\datos.properties"));
        } catch (IOException e) {
            System.out.println("error de cargar las properties datos" + e.getMessage());
        }
        
        try {
            jfLoginProps.load(new FileInputStream("D:\\Documentos\\NetBeansProjects\\contratacion\\src\\main\\java\\packagesproperties\\jf_login.properties"));
        } catch (IOException e) {
            System.out.println("error de cargar las properties jf_admin" + e.getMessage());
        }
   

     }
    
    /**
     * Creates new form Login
     */
    public JF_Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        txtPasword = new javax.swing.JPasswordField();
        txtUsername = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setResizable(false);

        lblUsuario.setText("Usuario");

        lblContraseña.setText("Contraseña");

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPasword, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnIngresar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(lblContraseña)))
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lblContraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPasword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnIngresar)
                .addGap(15, 15, 15))
        );

        txtUsername.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
   
    
    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // Leer el fichero de propiedades

        cargarproperties();

        // captura de datos del formulario login
        String usuario = txtUsername.getText();
        String contraseña = new String(txtPasword.getPassword());

        if (usuario.isEmpty()) {
            String mensajeu = jfLoginProps.getProperty("mensaje.campousuariovacio");

            JOptionPane.showMessageDialog(null, mensajeu, "Alerta", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (contraseña.isEmpty()) {
            String mensajec = jfLoginProps.getProperty("mensaje.campocontraseñavacio");

            JOptionPane.showMessageDialog(null, mensajec, "Alerta", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Consulta a la base de datos para verificar las credenciales   
        try {
            // Obtener la instancia de la conexión
            Connection conexion = Conexion.getInstance(datosProps).getConnection();

//            System.out.println(conexion);
//
//            System.out.println(datosProps);

            // Obtener la consulta SQL
            String consulta = jfLoginProps.getProperty("db.consultalogin");

//            System.out.println(consulta);

            // Crear la consulta preparada
            PreparedStatement consultasql = conexion.prepareStatement(consulta);

            consultasql.setString(1, usuario);
            consultasql.setString(2, contraseña);

            ResultSet resultado = consultasql.executeQuery();

            if (resultado.next()) {
                String hash = resultado.getString("hash");

                boolean passwordMatches = BCrypt.checkpw(contraseña, hash);

//                System.out.println(passwordMatches);
                if (passwordMatches) {
                    String mensajeiniciosesionexitoso = jfLoginProps.getProperty("mensaje.iniciodesesionexitoso");
                    JOptionPane.showMessageDialog(null, mensajeiniciosesionexitoso + usuario);
                    // Aquí puedes redirigir a otra ventana o realizar acciones posteriores al inicio de sesión

                    if (resultado.getString("rol").equals("admin")) {
                        JF_Admin newframe = new JF_Admin();

                        newframe.setVisible(true);

                        this.dispose();

//                       
                    } else if (resultado.getString("rol").equals("user")) {
                        JF_Usuario newframe = new JF_Usuario();

                        newframe.setVisible(true);

                        this.dispose();

                    } else {
                        String notienesrol = jfLoginProps.getProperty("mensaje.notienesrol");

                        JOptionPane.showMessageDialog(null, notienesrol, "Alerta", JOptionPane.ERROR_MESSAGE);
                    }

                } else {

                    String nocoicidehash = jfLoginProps.getProperty("mensaje.contraseñahashnocoincide");

                    JOptionPane.showMessageDialog(null, nocoicidehash, "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                String iniciosecionfallido = jfLoginProps.getProperty("mensaje.iniciosecionfallido");
                JOptionPane.showMessageDialog(null, iniciosecionfallido, "Error", JOptionPane.ERROR_MESSAGE);
            }
            conexion.close();
        } catch (SQLException e) {
            String erroriniciosesion = jfLoginProps.getProperty("mensaje.erroriniciarsesión");
            System.out.println(erroriniciosesion + e.getMessage());
            JOptionPane.showMessageDialog(null, erroriniciosesion, "ERROR", JOptionPane.ERROR_MESSAGE);
        }

   
    }//GEN-LAST:event_btnIngresarActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Login().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtPasword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}

















